name: Build APK with Buildozer

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            git zip unzip \
            openjdk-11-jdk \
            android-sdk \
            android-sdk-build-tools \
            android-sdk-platform-tools \
            android-sdk-cmdline-tools-latest \
            autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libncursesw5-dev \
            cmake libffi-dev libssl-dev

        echo "ANDROID_SDK_ROOT=/usr/lib/android-sdk" >> $GITHUB_ENV
        echo "PATH=$PATH:/usr/lib/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_ENV

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython==0.29.19

    - name: Setup Android SDK
      run: |
        yes | sdkmanager --licenses
        sdkmanager "build-tools;33.0.0" "platforms;android-33"

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Orange-Money-APK
        path: bin/*.apk
