name: Build APK with Buildozer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-11-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        pip install --upgrade pip
        pip install buildozer cython==0.29.19 virtualenv

    - name: Build APK
      run: |
        buildozer -v android debug
        cp bin/*.apk .

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Orange-Money-APK
        path: .apk
