name: Build APK with Buildozer

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Python version
        run: python --version
        
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            ccache \
            libncurses6 \
            libstdc++6 \
            zlib1g-dev \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            libjpeg-dev \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            wget

      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade pip
          pip install buildozer cython
          
      - name: Install Android SDK and accept licenses
        run: |
          mkdir -p $HOME/.android
          touch $HOME/.android/repositories.cfg
          yes | sdkmanager --licenses || true

      - name: Initialize and Build APK
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
          buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mobilemoney-apk
          path: bin/*.apk
