name: Build APK with Buildozer

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Check Python version
        run: python --version
        
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            ccache \
            libncurses6 \
            libstdc++6 \
            zlib1g-dev \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            libjpeg-dev \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            wget \
            git \
            autoconf \
            automake \
            libtool \
            pkg-config
            
      - name: Install Buildozer and dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython
          
      - name: Set up Android SDK
        run: |
          # Créer les répertoires nécessaires
          mkdir -p $HOME/.android
          mkdir -p $HOME/.buildozer/android/platform
          
          # Créer le fichier repositories.cfg
          touch $HOME/.android/repositories.cfg
          
          # Télécharger et installer Android SDK Command Line Tools
          cd $HOME/.buildozer/android/platform
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip commandlinetools-linux-11076708_latest.zip
          
          # Créer la structure attendue par Buildozer
          mkdir -p android-sdk/cmdline-tools
          mv cmdline-tools android-sdk/cmdline-tools/latest
          
          # Créer aussi l'ancien répertoire tools/bin pour la compatibilité
          mkdir -p android-sdk/tools/bin
          cp android-sdk/cmdline-tools/latest/bin/sdkmanager android-sdk/tools/bin/
          
          # Définir les variables d'environnement
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          export ANDROID_HOME=$ANDROID_SDK_ROOT
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/tools/bin
          
          # Accepter les licences et installer les packages nécessaires
          cd android-sdk/cmdline-tools/latest/bin
          yes | ./sdkmanager --licenses
          ./sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2" "cmdline-tools;latest"
          
      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: ~/.buildozer
          key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            buildozer-${{ runner.os }}-
            
      - name: Cache Buildozer dependencies
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: buildozer-deps-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            buildozer-deps-${{ runner.os }}-
            
      - name: Initialize Buildozer
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
          
      - name: Configure Buildozer spec
        run: |
          # Modifier buildozer.spec pour utiliser les bonnes versions
          sed -i 's/^#android.api = .*/android.api = 33/' buildozer.spec || echo "android.api = 33" >> buildozer.spec
          sed -i 's/^#android.minapi = .*/android.minapi = 21/' buildozer.spec || echo "android.minapi = 21" >> buildozer.spec
          sed -i 's/^#android.ndk = .*/android.ndk = 25b/' buildozer.spec || echo "android.ndk = 25b" >> buildozer.spec
          sed -i 's/^#android.sdk = .*/android.sdk = 33/' buildozer.spec || echo "android.sdk = 33" >> buildozer.spec
          
      - name: Build APK
        run: |
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          export ANDROID_HOME=$ANDROID_SDK_ROOT
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/tools/bin
          
          # Vérifier que sdkmanager est accessible
          which sdkmanager || echo "sdkmanager introuvable dans PATH"
          ls -la $ANDROID_SDK_ROOT/tools/bin/sdkmanager || echo "sdkmanager introuvable dans tools/bin"
          
          buildozer android debug
          
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mobilemoney-apk
          path: bin/*.apk
          if-no-files-found: error
          
      - name: List generated files (debug)
        if: always()
        run: |
          echo "Contenu du répertoire bin:"
          ls -la bin/ || echo "Le répertoire bin n'existe pas"
          echo "Structure du projet:"
          find . -name "*.apk" -type f
